# Conventional port for discovery server is '8761'.
server:
  port: 8761

# Register self as a client to discovery server (itself also).
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Must match the name of the configuration files stored in the config server (this includes profile specific configuration files).
spring:
  application:
    name: discovery-server

# Defaults to 'http://localhost:8888' if discovery is not enabled otherwise use entries from discovery server.
  config:
    import: 'optional:configserver:'

# Use the discovery server to find other config server instances so that URL does not have to be set in 'spring.config.import'.
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server