# Set port for service-registry peer2.
server:
  port: 8762

# Register self as a client to service-registry peer1. Update C:\Windows\System32\drivers\etc wnen using Windows.
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/