# Conventional port for discovery server is '8761'.
server:
  port: 8761

# Prevent self from registering as a client to Eureka server. Only use this when there's only one instance of discovery server.
eureka:
  client:
    register-with-eureka: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

# Must match the name of the configuration files stored in the config server. Includes profile specific configuration files.
spring:
  application:
    name: discovery-server

# Defaults to 'http://localhost:8888' if discovery is not enabled.
  config:
    import: 'optional:configserver:'
  
# Use the Eureka server to find other config server instances so that URL does not have to be set in 'spring.config.import'.
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
