# Conventional port for service-registry is '8761'.
server:
  port: 8761

# Register self as a client to service-registry (also itself).
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Must match the name of the configuration files managed by config-server (this includes profile specific configuration files).
spring:
  application:
    name: service-registry

# Defaults to 'http://localhost:8888' if discovery is not enabled otherwise use entries from service-registry.
  config:
    import: 'optional:configserver:'

# Use service-registry to find other config-server instances so that URL does not have to be set in 'spring.config.import'.
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server